#!/bin/csh  
# 기본적인 tcshell환경에서 c쉘을 이용하는 방법이다.

set values = (4 2 7 9 6 5 8 3)
echo $values  # 변수 값을 출력할 때 echo를 사용하며, 이때 스크립트에는 변수의 주소를 ‘$’를 입력한다. 

@ i = 1 #변수에 정수를 입력시, ‘@’를 붙여 참조한다.
@ j = 1

while ($i < $#values)
	@ j = $i
	while($j < $#values)
	  @ k = $j + 1 #항상 변수 사용시 값을 이용하려면 ‘$’ 붙여주어야 한다.
	    if($values[$i] > $values[$k]) then
  	      set tmp = $values[$i]  #값을 변수에 넣을시 ‘set‘이용하고 이때 변수에 ‘$‘ 안붙여도 된다.
	      set values[$i] = $values[$k]  # 값을 입력시 배열의 변수도 ‘$’를 붙여주어야 한다. 
	      set values[$k] = $tmp
		endif
			@ j ++
	end
	@ i ++
end
	echo $values


@ i = 1
@ j = $#values

foreach x ($values[$i-])
	set tmp2 = $x
	set x = $values[$j] #foreach 사용시 x는 값을 복사하는 것이 아니라, 주소 자체를 참조한다.
	set values[$j] = $tmp2
	endif
	@ j --
end

	echo $values
